[project]
name = "fundotstacks"
description = "Decentralized crowdfunding platform on Stacks"
authors = []
telemetry = false
cache_dir = ".cache"
requirements = []
boot_contracts = []

[contracts.campaign-core]
path = "contracts/campaign-core.clar"
clarity_version = 4
epoch = "3.3"

[contracts.campaign-core-v2]
path = "contracts/campaign-core-v2.clar"
clarity_version = 4
epoch = "3.3"

[contracts.milestone-manager]
path = "contracts/milestone-manager.clar"
clarity_version = 4
epoch = "3.3"

[contracts.nft-rewards]
path = "contracts/nft-rewards.clar"
clarity_version = 4
epoch = "3.3"

[contracts.refund-handler]
path = "contracts/refund-handler.clar"
clarity_version = 4
epoch = "3.3"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
